% LIB
%
% Files
%   Bragg_peak          - Bragg_peak.m
%   ConditionDopRSWIC   - ConditionDopRSWIC.m
%   create_2d_spectrum  - create_2d_spectrum.m
%   createfigure4x4     - Auto-generated by MATLAB on 11-Jul-2021 18:21:16
%   createfigure8x2     - Auto-generated by MATLAB on 11-Jul-2021 18:10:32
%   DirFun              - DirFun.m
%   dopLipa_sub         - dopLipa_sub.m
%   dopLipaS            - dopLipaS.m
%   findSNR             - findSNR.m
%   gamma_mm_depth      - gamma_mm_depth
%   Gauss_fit           - Gauss_fit.m
%   hfr_noise           - hfr_noise.m
%   Inverted_2D_DirSpec - Inverted_2D_DirSpec.m
%   PXYint              - PXYint.m
%   PXYsideband         - PXYsideband.m
%   specSwellRSWIC      - specSwellRSWIC.m
%   spectral_noise      - spectral_noise.m
%   specWindRSWIC       - specWindRSWIC.m
%   spreadparam         - spreadparam.m
%   swell_peak          - swell_peak.m
%   swell_singular      - swell_singular.m
%   waveparams          - waveparams.m
%   waveparams3         - waveparams3.m
%   weightf_barrick     - weightf_barrick.m
%   wn2ndRSWIC          - wn2ndRSWIC.m
%   wrap180             - wrap180.m
%   wspecRSWIC_hybrid   - wspecRSWIC_hybrid.m
