function createfigure4x4(xdata1, ydata1, zdata1, zdata2, zdata3,...
    zdata4, zdata5, zdata6, zdata7, zdata8, zdata9,...
    zdata10, zdata11, zdata12, zdata13, zdata14, zdata15, zdata16,xdata2, ydata2)

%  Auto-generated by MATLAB on 11-Jul-2021 18:21:16

% Create figure
figure1 = figure('Color',[1 1 1]);
colormap(jet(128));

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.07 0.7225 0.2075 0.1975]);
hold(axes1,'on');
% Create contour
% contour(xdata1,ydata1,zdata1,'Parent',axes1,...
%     'LevelList',[0.00319630182485813 0.00639260364697104 0.00958890546908394 0.0127852072911968 0.0159815091133098 0.0191778109354227 0.0223741127575356 0.0255704145796485 0.0287667164017614 0.0319630182238743]);
% Create text
contour(xdata1,ydata1,zdata1,'Parent',axes1,...
    'LevelList',[0.004:.002:.06]);
text('Parent',axes1,'FontSize',12,'String','A','Position',[0.06 340 0]);
% Create ylabel
ylabel('direction(^o)','FontName','arial');
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{},'YMinorTick','on','YTick',[0 90 180 270 360],'YTickLabel',...
    {'0','90','180','270','360'});
caxis([0 0.06])
ax1 = axis;

% Create axes
axes2 = axes('Parent',figure1,'Position',[0.07 0.515 0.2075 0.1975]);
hold(axes2,'on');
% Create contour
% contour(xdata2,ydata2,zdata2,'Parent',axes2,...
%     'LevelList',[0.00631037132253743 0.0126207426309912 0.0189311139394449 0.0252414852478986 0.0315518565563524 0.0378622278648061 0.0441725991732598 0.0504829704817136 0.0567933417901673 0.063103713098621]);
% Create text
contour(xdata2,ydata2,zdata2,'Parent',axes2,...
    'LevelList',[0.004:.002:.06]);
text('Parent',axes2,'FontSize',12,'String','A','Position',[0.06 340 0]);
% Create ylabel
ylabel('direction(^o)','FontName','arial');
% Create xlabel
xlabel('f (Hz)','FontName','arial');
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{'0.1','0.2','0.3'},'YMinorTick','on','YTick',...
    [0 90 180 270 360],'YTickLabel',{'0','90','180','270','360'});
% Create colorbar
colorbar(axes2,'north');
caxis([0 0.06])
axis(ax1)

% Create axes
axes3 = axes('Parent',figure1,'Position',[0.3025 0.7225 0.2075 0.1975]);
hold(axes3,'on');
% Create contour
contour(xdata1,ydata1,zdata3,'Parent',axes3,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes3,'FontSize',12,'String','B','Position',[0.06 340 0]);
box(axes3,'on');
% Set the remaining axes properties
set(axes3,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{},'YMinorTick','on','YTick',[0 90 180 270 360],'YTickLabel',...
    {});
caxis([0 0.06])
axis(ax1)

% Create axes
axes4 = axes('Parent',figure1,'Position',[0.3025 0.515 0.2075 0.1975]);
hold(axes4,'on');
% Create contour
contour(xdata2,ydata2,zdata4,'Parent',axes4,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes4,'FontSize',12,'String','B','Position',[0.06 340 0]);
% Create xlabel
xlabel('f (Hz)','FontName','arial');
box(axes4,'on');
% Set the remaining axes properties
set(axes4,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{'0.1','0.2','0.3'},'YMinorTick','on','YTick',...
    [0 90 180 270 360],'YTickLabel',{});
caxis([0 0.06])
axis(ax1)

% Create axes
axes5 = axes('Parent',figure1,'Position',[0.535 0.7225 0.2075 0.1975]);
hold(axes5,'on');
% Create contour
contour(xdata1,ydata1,zdata5,'Parent',axes5,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes5,'FontSize',12,'String','C','Position',[0.06 340 0]);
box(axes5,'on');
% Set the remaining axes properties
set(axes5,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{},'YMinorTick','on','YTick',[0 90 180 270 360],'YTickLabel',...
    {});
caxis([0 0.06])
axis(ax1)

% Create axes
axes6 = axes('Parent',figure1,'Position',[0.535 0.515 0.2075 0.1975]);
hold(axes6,'on');
% Create contour
contour(xdata2,ydata2,zdata6,'Parent',axes6,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes6,'FontSize',12,'String','C','Position',[0.06 340 0]);
% Create xlabel
xlabel('f (Hz)','FontName','arial');
% ylim(axes6,[0 360]);
box(axes6,'on');
% Set the remaining axes properties
set(axes6,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{'0.1','0.2','0.3'},'YMinorTick','on','YTick',...
    [0 90 180 270 360],'YTickLabel',{});
caxis([0 0.06])
axis(ax1)

% Create axes
axes7 = axes('Parent',figure1,'Position',[0.7675 0.7225 0.2075 0.1975]);
hold(axes7,'on');
% Create contour
contour(xdata1,ydata1,zdata7,'Parent',axes7,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes7,'FontSize',12,'String','D','Position',[0.06 340 0]);
% Create text
text('Parent',axes7,'String','In Situ','Position',[0.24 330 0]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[0.05 0.35]);
box(axes7,'on');
% Set the remaining axes properties
set(axes7,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{},'YMinorTick','on','YTick',[0 90 180 270 360],'YTickLabel',...
    {});
caxis([0 0.06])
axis(ax1)

% Create axes
axes8 = axes('Parent',figure1,'Position',[0.7675 0.515 0.2075 0.1975]);
hold(axes8,'on');
% Create contour
contour(xdata2,ydata2,zdata8,'Parent',axes8,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes8,'FontSize',12,'String','D','Position',[0.06 340 0]);
% Create text
text('Parent',axes8,'String','Inverted','Position',[0.24 330 0]);
% Create xlabel
xlabel('f (Hz)','FontName','arial');
box(axes8,'on');
% Set the remaining axes properties
set(axes8,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{'0.1','0.2','0.3'},'YMinorTick','on','YTick',...
    [0 90 180 270 360],'YTickLabel',{});
caxis([0 0.06])
axis(ax1)

% Create axes
axes9 = axes('Parent',figure1,'Position',[0.07 0.3075 0.2075 0.1975]);
hold(axes9,'on');
% Create contour
contour(xdata1,ydata1,zdata9,'Parent',axes9,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes9,'FontSize',12,'String','E','Position',[0.06 340 0]);
% Create ylabel
ylabel('direction(^o)','FontName','arial');
box(axes9,'on');
% Set the remaining axes properties
set(axes9,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{},'YMinorTick','on','YTick',[0 90 180 270 360],'YTickLabel',...
    {'0','90','180','270','360'});
caxis([0 0.06])
axis(ax1)

% Create axes
axes10 = axes('Parent',figure1,'Position',[0.07 0.1 0.2075 0.1975]);
hold(axes10,'on');
contour(xdata2,ydata2,zdata10,'Parent',axes10,...
    'LevelList',[0.004:.002:.06]);
text('Parent',axes10,'FontSize',12,'String','E','Position',[0.06 340 0]);
ylabel('direction(^o)','FontName','arial');
xlabel('f (Hz)','FontName','arial');
box(axes10,'on');
% Set the remaining axes properties
set(axes10,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{'0.1','0.2','0.3'},'YMinorTick','on','YTick',...
    [0 90 180 270 360],'YTickLabel',{'0','90','180','270','360'});
caxis([0 0.06])
axis(ax1)

% Create axes
axes11 = axes('Parent',figure1,'Position',[0.3025 0.3075 0.2075 0.1975]);
hold(axes11,'on');
contour(xdata1,ydata1,zdata11,'Parent',axes11,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes11,'FontSize',12,'String','F','Position',[0.06 340 0]);
box(axes11,'on');
% Set the remaining axes properties
set(axes11,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{},'YMinorTick','on','YTick',[0 90 180 270 360],'YTickLabel',...
    {});
caxis([0 0.06])
axis(ax1)

% Create axes
axes12 = axes('Parent',figure1,'Position',[0.3025 0.1 0.2075 0.1975]);
hold(axes12,'on');
% Create contour
contour(xdata2,ydata2,zdata12,'Parent',axes12,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes12,'FontSize',12,'String','F','Position',[0.06 340 0]);
% Create xlabel
xlabel('f (Hz)','FontName','arial');
box(axes12,'on');
% Set the remaining axes properties
set(axes12,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{'0.1','0.2','0.3'},'YMinorTick','on','YTick',...
    [0 90 180 270 360],'YTickLabel',{});
caxis([0 0.06])
axis(ax1)

% Create axes
axes13 = axes('Parent',figure1,'Position',[0.535 0.3075 0.2075 0.1975]);
hold(axes13,'on');
% Create contour
contour(xdata1,ydata1,zdata13,'Parent',axes13,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes13,'FontSize',12,'String','G','Position',[0.06 340 0]);
box(axes13,'on');
% Set the remaining axes properties
set(axes13,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{},'YMinorTick','on','YTick',[0 90 180 270 360],'YTickLabel',...
    {});
caxis([0 0.06])
axis(ax1)

% Create axes
axes14 = axes('Parent',figure1,'Position',[0.535 0.1 0.2075 0.1975]);
hold(axes14,'on');
% Create contour
contour(xdata2,ydata2,zdata14,'Parent',axes14,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes14,'FontSize',12,'String','G','Position',[0.06 340 0]);
% Create xlabel
xlabel('f (Hz)','FontName','arial');
box(axes14,'on');
% Set the remaining axes properties
set(axes14,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{'0.1','0.2','0.3'},'YMinorTick','on','YTick',...
    [0 90 180 270 360],'YTickLabel',{});
caxis([0 0.06])
axis(ax1)

% Create axes
axes15 = axes('Parent',figure1,'Position',[0.7675 0.3075 0.2075 0.1975]);
hold(axes15,'on');
% Create contour
contour(xdata1,ydata1,zdata15,'Parent',axes15,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes15,'FontSize',12,'String','H','Position',[0.06 340 0]);
% Create text
text('Parent',axes15,'String','In Situ','Position',[0.24 330 0]);
% Create xlabel
xlabel('f (Hz)','FontName','arial');
box(axes15,'on');
% Set the remaining axes properties
set(axes15,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{},'YMinorTick','on','YTick',[0 90 180 270 360],'YTickLabel',...
    {});
caxis([0 0.06])
axis(ax1)

% Create axes
axes16 = axes('Parent',figure1,'Position',[0.7675 0.1 0.2075 0.1975]);
hold(axes16,'on');
% Create contour
contour(xdata2,ydata2,zdata16,'Parent',axes16,...
    'LevelList',[0.004:.002:.06]);
% Create text
text('Parent',axes16,'FontSize',12,'String','H','Position',[0.06 340 0]);
% Create text
text('Parent',axes16,'String','Inverted','Position',[0.24 330 0]);
% Create xlabel
xlabel('f (Hz)','FontName','arial');
box(axes16,'on');
% Set the remaining axes properties
set(axes16,'BoxStyle','full','FontName','arial','Layer','top','LineWidth',...
    0.8,'TickLength',[0.02 0.02],'XMinorTick','on','XTick',[0.1 0.2 0.3],...
    'XTickLabel',{'0.1','0.2','0.3'},'YMinorTick','on','YTick',...
    [0 90 180 270 360],'YTickLabel',{});
caxis([0 0.06])
axis(ax1)
